### ISSUE TITLE
如何修改请求的路由

### ISSUE THREAD

**Issue by lazytooo** [wyt1215819315/autoplan#101]
本地服务器存在nginx反向代理，根据路由重定向到自己的网页，想通过自定义路由，进入当前项目，需要在哪个文件里添加路由前缀？
目前访问路径：https://xxxx.xxx/login进入页面。
我想修改成：https://xxxx.xxx/auto_plan/login进入页面。

**Comment by yanisCC** [comment]
请尝试在 [autoplan/application-example.yml](https://github.com/wyt1215819315/autoplan/blob/master/application-example.yml) 文件中修改：
```
server:
  #服务器端口
  port: 26666
```
改为：
```
server:
  #服务器端口
  port: 26666
  servlet:
    context-path: /auto_plan
```
